This is makeindex, version 2.14 [02-Oct-2002] (kpathsea + Thai support).
Scanning style file ./tpmmanager.ist..............done (14 attributes redefined, 0 ignored).
Scanning input file tpmmanager.acr....done (28 entries accepted, 0 rejected).
Sorting entries....done (132 comparisons).
Generating output file tpmmanager.acn....done (41 lines written, 0 warnings).
Output written in tpmmanager.acn.
Transcript written in tpmmanager.alg.
